#!/bin/bash
# transform channel names to simple, svc-id based names in channels.conf
# Usage: s2scan -a 0 -p -v -c | $0 -c

PREFIX='BS'
if [ x"$1" == 'x-c' ]; then
  PREFIX='CS'
fi
exec /bin/sed -e 's/^\([^#:][^:]*\):\([^:]*\):\([0-9a-fA-F]*\)/# \1\n'$PREFIX'\3:\2:\3/'
