obj-$(CONFIG_DVB_PTX_COMMON)	+= ptx_common.o
obj-$(CONFIG_DVB_PT3)		+= pt3.o
obj-$(CONFIG_DVB_PXQ3PE)	+= pxq3pe.o

ccflags-y += -Idrivers/media/dvb-core -Idrivers/media/dvb-frontends -Idrivers/media/tuners

