pt3-objs	:= pt3_pci.o ptx_common.o
pxq3pe-objs	:= pxq3pe_pci.o ptx_common.o

obj-$(CONFIG_DVB_PT3)		+= pt3.o
obj-$(CONFIG_DVB_PXQ3PE)	+= pxq3pe.o

ccflags-y += -Idrivers/media/dvb-core -Idrivers/media/dvb-frontends -Idrivers/media/tuners

